# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate


####################################################
#      LINKS TO INDIVUAL CONFIGURATION FILES       #
####################################################

#https://home-assistant.io/docs/configuration/splitting_configuration/

recorder: !include recorder.yaml
influxdb: !include influxdb.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
switch: !include switches.yaml
climate: !include climates.yaml
speedtestdotnet: !include speedtestdotnet.yaml

####################################################
#                 Utility Meter                    #
####################################################

#https://www.home-assistant.io/integrations/utility_meter/

utility_meter:
  hourly_water_consumption:
    source: sensor.water_consumption
    cycle: hourly
  daily_water_consumption:
    source: sensor.water_consumption
    cycle: daily
  monthly_water_consumption:
    source: sensor.water_consumption
    cycle: monthly    


####################################################
#                    SMART IR                      #
####################################################

#https://github.com/smartHomeHub/SmartIR

smartir:

####################################################
#               Generic IP Camera                  #
####################################################

#https://www.home-assistant.io/integrations/generic_ip_camera
# camera:
#   - platform: generic
#     still_image_url: http://10.0.0.141:8080/photoaf.jpg
#     verify_ssl: false
#     name: watermeter