esphome:
  name: water_meter_mini
  platform: ESP8266
  board: d1_mini
  includes:
    - enbra_wmbus_08.h
  libraries:
    - chrono

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Water Meter Mini"
    password: "YsmMvvPlnY3U"

captive_portal:

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:

ota:

web_server:
  port: 80

uart:
  id: uart_bus
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 9600
  
sensor:
- platform: custom
  lambda: |-
    auto enbra_sensor = new EnbraWmbus08(id(uart_bus));
    App.register_component(enbra_sensor);
    return {enbra_sensor};
  sensors:
    name: "Water consumption"
    unit_of_measurement: l
    accuracy_decimals: 0